---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bibliometrix)
library(tidyverse)
library(ggtext)
library(glue)
library(ggrepel)
library(countrycode)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rmapshaper)
library(CoordinateCleaner)
library(igraph)
library(ggraph)
library(tidygraph)
library(patchwork)
library(cowplot)
```

```{r}
# load 10_flow_chart
load(file="rdata/10_flow_chart_mafld.RData")
```

```{r}
# create flow chart for literature search and selection
s2 <- tibble(x= 0:150, y= 0:150)  %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(0, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(0, 100, 10)) +
  theme_linedraw()
```

```{r}
# create boxes for literature databases
s2 <- s2 +
  geom_rect(xmin = 0, xmax=40, ymin=145, ymax=150, color='black', fill="#fddaec", size=0.3) +
  annotate('text', x = 1.5, y = 147.5,
           label= 'Records identified from\nPubMed (n = 19013)',
           size=2.8, hjust = 0) +
  geom_rect(xmin = 50, xmax=90, ymin=145, ymax=150, color='black', fill='#ccebc5', size=0.3) +
  annotate('text', x = 51.5, y = 147.5,
           label= 'Records identified from\nWeb of Science (n = 22893)',
           size=2.8, hjust = 0)+
  geom_rect(xmin = 100, xmax=140, ymin=145, ymax=150, color='black', fill='#fed9a6', size=0.3) +
  annotate('text', x = 101.5, y = 147.5,
           label= 'Records identified from\nScopus (n = 19681)',
           size = 2.8, hjust = 0)
```

```{r}
# add first exclusion boxes
s2 <- s2 +
  geom_rect(xmin = 10, xmax = 50, ymin = 122.5, ymax = 142.5, color='black', fill="white", size=0.3) +
  geom_rect(xmin = 60, xmax = 100, ymin = 122.5, ymax = 142.5, color='black', fill='white', size=0.3) +
  geom_rect(xmin = 110, xmax = 150, ymin = 122.5, ymax= 142.5, color='black', fill='white', size=0.3)
```

```{r}
# contents of the exclusion box
s2 <- s2 +
  annotate('text', x = 11.5, y = 141,
           label= "Records excluded (n = 4142):\n   Duplicates (n = 863)\n   No NAFLD/NASH term\n   (n = 2017)\n   Outside 2015-2020 (n = 663)\n   Not English (n = 506)\n   Ineligible publication type\n   (n = 93)",
           size = 2.8, hjust = 0, vjust = 1) +
  annotate('text', x = 61.5, y = 141,
           label= "Records excluded (n = 8015):\n   No NAFLD/NASH term\n   (n = 2324)\n   Outside 2015-2020 (n = 260)\n   Not English (n = 304)\n   Ineligible publication type\n   (n = 5124)\n   Incorrect indexing (n = 1)\n   Duplicates (n = 2)",
           size = 2.8, hjust = 0, vjust = 1) +
  annotate('text', x = 111.5, y = 141,
           label= "Records excluded (n = 4435):\n   No NAFLD/NASH term\n   (n = 2510)\n   Not English (n = 1232)\n   Ineligible publication type\n   (n = 678)\n   Incorrect indexing (n = 1)\n   Duplicates (n = 14)"   ,
           size = 2.8, hjust = 0, vjust = 1)
```

```{r}
# add vertical arrows for literature selection in each database
s2 <- s2 +
  geom_segment(x = 5, xend = 5, y = 145, yend = 120.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 55, xend = 55, y = 145, yend = 120.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 105, xend = 105, y = 145, yend= 120.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))
```

```{r}
# add horizontal arrows for first exclusion
s2 <- s2 +
  geom_segment(x = 5, xend = 9.5, y = 132.5, yend=132.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 55, xend = 59.5, y = 132.5, yend=132.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 105, xend = 109.5, y = 132.5, yend=132.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))
```

```{r}
# add box after literature selection in each database
s2 <- s2 +
  geom_rect(xmin = 0, xmax=40, ymin=  115, ymax = 120, color='black', fill="#fddaec", size=0.3) +
  annotate('text', x = 1.5, y = 117.5,label= 'Eligible records from\nPubMed (n = 14871)', size= 2.8, hjust = 0) +
  geom_rect(xmin = 50, xmax=90, ymin=  115, ymax = 120, color='black', fill='#ccebc5', size=0.3) +
  annotate('text', x = 51.5, y = 117.5,label= 'Eligible records from\nWeb of Science (n = 14878)', size=2.8, hjust  = 0)+
  geom_rect(xmin = 100, xmax=140, ymin= 115, ymax = 120, color='black', fill='#fed9a6', size=0.3) +
  annotate('text', x = 101.5, y = 117.5,label= 'Eligible records from\nScopus (n = 15246)', size=2.8, hjust = 0)
```

```{r}
# add lines and arrows for merging three datasets
s2 <- s2 +
  geom_segment(x = 5, xend = 5, y = 115, yend = 112.5, size=0.3, linejoin = "mitre", lineend = "butt")+
  geom_segment(x = 55, xend = 55, y = 115, yend = 110.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 105, xend = 105, y = 115, yend = 112.5, size=0.3, linejoin = "mitre", lineend = "butt")+
  geom_segment(x = 5, xend = 105, y = 112.5, yend = 112.5, size=0.3, linejoin = "mitre", lineend = "butt")
```

```{r}
# add box after merging three datasets
s2 <- s2 +
  geom_rect(xmin = 50, xmax=90, ymin=  105, ymax = 110, color='black', fill = "white", size=0.3) +
  annotate('text', x = 51.5, y = 107.5,label= 'Records included (n = 16433)', size=2.8, hjust  = 0)
```

```{r}
# add exclusion after merge
s2 <- s2 +
  geom_segment(x = 55, xend = 55, y = 105, yend = 90.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 55, xend = 59.5, y = 100, yend = 100, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_rect(xmin = 60, xmax= 100, ymin=  92.5, ymax = 102.5, color='black',fill = "white", size=0.3) +
  annotate('text', x = 61.5, y = (92.5+102.5)/2,label= 'Records excluded (n = 6012):\n   Duplicates (n = 148)\n   Outside 2016-2019\n   (n = 5864)', size=2.8, hjust  = 0)
```

```{r}
# add box for inclusion
s2 <- s2 +
  geom_rect(xmin = 50, xmax = 90, ymin=  85, ymax = 90, color='black', fill = "white", size=0.3) +
  annotate('text', x = 51.5, y = 87.5,label= 'Records included (n = 10421)', size=2.8, hjust  = 0)
```


```{r}
# downstream middle (keyword)
s2 <- s2 +
 geom_segment(x = 55, xend = 55, y = 85, yend = 75.5, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
  geom_segment(x = 55, xend = 59.5, y = 80, yend = 80, size=0.3, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1, "mm"), type= "closed"))+
   geom_rect(xmin = 60, xmax = 100, ymin=  77.5, ymax = 82.5, color='black', fill = "white", size=0.3) +
  annotate('text', x = 61.5, y = 80,label= 'Records excluded (n = 2853):\n   Missing keywords (n = 2853)', size=2.8, hjust  = 0)+
  geom_rect(xmin = 50, xmax = 90, ymin=  70, ymax = 75, color='black', fill = "white", size=0.3) +
  annotate('text', x = 51.5, y = 72.5,label= 'Records for keyword analysis\n(n = 7568)', size=2.8, hjust  = 0)
```


```{r}
s2 <- s2 +
  scale_x_continuous(expand = c(0, 0), limits = c(-2, 152)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(68, 152))+
  theme_void()+
  labs(caption = "<span style = 'font-family:sans'><b>Fig. S2</b></span> Flow chart of selection process for NAFLD literature")+
  theme(plot.caption = element_markdown(family = "serif", size = 10, hjust = 0),
        plot.caption.position =  "panel",
        plot.margin = margin(c(23, 23, 94, 23), unit = "mm"))
```

```{r}
ggsave("figure/FigS2.pdf", s2, width = 210, height = 297, units = "mm")
```

```{r}
save.image("rdata/11_flow_chart_nafld.RData")
```
