---
title: "MAFLD"
output: html_document
date: "2024-06-17"
---

```{r}
library(bibliometrix)
library(tidyverse)
```


```{r}
rds_name_p <- list.files("rds_nafld/", pattern= "pubmed")
rds_name_p
```

```{r}
rds_path_p <- paste0("rds_nafld/", rds_name_p)
rds_path_p
```

```{r}
# create function to  count the number of records in each file
count_record <- function(name, path){
  df <- readRDS(path)
  return(tibble(file = name, n_row = nrow(df)))
}
```

```{r}
# check records in each pubmed rds
df_pubmed_count <- map2(rds_name_p, rds_path_p, count_record) %>% list_rbind()
df_pubmed_count
# the same as reported by pubmed
```


```{r}
# combine and save pubmed RDS
map(rds_path_p, readRDS) %>% list_rbind() %>%
  saveRDS("rds_nafld/pubmed_nafld_all")
```


```{r}
rds_name_w <- list.files("rds_nafld/", pattern= "wos")
rds_name_w
```

```{r}
rds_path_w <- paste0("rds_nafld/", rds_name_w)
rds_path_w
```

```{r}
# check records in each wos rds
df_wos_count <- map2(rds_name_w, rds_path_w, count_record) %>% list_rbind()
df_wos_count
# the same as reported by wos
```

```{r}
# combine and save pubmed RDS
map(rds_path_w, readRDS) %>% list_rbind() %>%
  saveRDS("rds_nafld/wos_nafld_all")
```


```{r}
rds_name_s <- list.files("rds_nafld/", pattern= "scopus")
rds_name_s
```

```{r}
rds_path_s <- paste0("rds_nafld/", rds_name_s)
rds_path_s
```

```{r}
# count records in scopus
count_record(rds_name_s, rds_path_s)
# the same as reported as Scopus
```

```{r}
# end of converting RDS
```
